name: Update News
on:
  push:
    branches:
      - main
  schedule:
      - cron: "0 5 * * 1-5"
jobs:
  fetch-news:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18.17.1
    steps:
      - name: "📥  Checkout repository"
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: "🔄  Cache node_modules"
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "🔧 Setup NodeJS ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "📦  Install CI dependencies"
        run: npm ci

      - name: "📰 Fetch News"
        run: npm run fetch

      - name: "Commit updated cache"
        uses: EndBug/add-and-commit@v9
        with:
            add: 'cache'
            message: '🤖 chore(cache):updated on ${{ github.sha }} [skip ci] 🤖'
      
      - name: "📰 Build News Page"
        run: |
          cp -r ./cache ./dist
          npm run build
  
      - name: Deploy to GhPages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
